forecast2023:
  lang: "ru"
  #fixme
  owm-api-key: 63aff41dd90c22e4314b07a1c08731db

management:
  endpoints:
    web:

      discovery:
        enabled: true
mapstruct:
  defaultComponentModel: spring
