spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/forecast2023
    username: forecast2023
    password:
    hikari:
      poolName: Hikari
      auto-commit: false