forecast2023:
  lang: "ru"
  #fixme
  owm-api-key: "null"

management:
  endpoints:
    web:
      #      exposure:
      #        #        include: ['health', 'prometheus']
      #        #        include: ['configprops', 'env', 'info', 'health', 'prometheus']
      #        include: '*'
      discovery:
        enabled: true

# todo
#springdoc:
#  api-docs:
#    groups:
#      enabled: true
#  show-actuator: true
#  swagger-ui:
#    tryItOutEnabled: true
#    url: /api.yml
#    enabled: true