forecast2023:
  lang: "ru"
  rest-api-url: 'http://localhost:8080/api/v1'
  obsolete: 60m
  data-points-reducer: default
  owm-api-key:

springdoc:
  api-docs:
    groups:
      enabled: true
spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update