forecast2023:
  lang: "ru"
  owm-api-key: 63aff41dd90c22e4314b07a1c08731db
  rest-api-url: 'http://localhost:8080/api/v1'
  obsolete: 60m
  data-points-reducer: default

springdoc:
  api-docs:
    groups:
      enabled: true
spring:
  jpa:
    open-in-view: false